public class L3270_Find_the_Key_of_the_Numbers {

    /*

    You are given three positive integers num1, num2, and num3.

    The key of num1, num2, and num3 is defined as a four-digit number such that:

    Initially, if any number has less than four digits, it is padded with leading zeros.
    The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
    Return the key of the three numbers without leading zeros (if any).



    Example 1:

    Input: num1 = 1, num2 = 10, num3 = 1000

    Output: 0

    Explanation:

    On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains "1000".

    The 1st digit of the key is min(0, 0, 1).
    The 2nd digit of the key is min(0, 0, 0).
    The 3rd digit of the key is min(0, 1, 0).
    The 4th digit of the key is min(1, 0, 0).
    Hence, the key is "0000", i.e. 0.

    Example 2:

    Input: num1 = 987, num2 = 879, num3 = 798

    Output: 777

    Example 3:

    Input: num1 = 1, num2 = 2, num3 = 3

    Output: 1

    1 <= num1, num2, num3 <= 9999

     */
    public int generateKey(int num1, int num2, int num3) {
        //        String num1Str = String.format("%04d", num1);
        //        String num2Str = String.format("%04d", num2);
        //        String num3Str = String.format("%04d", num3);
        //
        //        int res = 0;
        //        for (int i = 3; i >= 0; i--) {
        //            char c1 = num1Str.charAt(i);
        //            char c2 = num2Str.charAt(i);
        //            char c3 = num3Str.charAt(i);
        //            res *= 10;
        //            res += (Math.min(c1, Math.min(c2, c3))) - '0';
        //        }
        //
        //        return res;


        int res = 0;
        int pow = 0;
        int a = 0, b = 0, c = 0;
        while (num1 > 0 || num2 > 0 || num3 > 0) {
            if (num1 > 0) {
                a = num1 % 10;
            } else {
                a = 0;
            }

            if (num2 > 0) {
                b = num2 % 10;
            } else {
                b = 0;
            }

            if (num3 > 0) {
                c = num3 % 10;
            } else {
                c = 0;
            }

            res += Math.min(a, Math.min(b, c)) * (int) Math.pow(10, pow);

            num1 /= 10;
            num2 /= 10;
            num3 /= 10;
            pow++;
        }

        return res;
    }

    public static void main(String[] args) {

        L3270_Find_the_Key_of_the_Numbers s = new L3270_Find_the_Key_of_the_Numbers();
        long sysDate1 = System.currentTimeMillis();

        int num1 = 1;
        int num2 = 12;
        int num3 = 3;

        int res = s.generateKey(num1, num2, num3);
        System.out.println(res);

        long sysDate2 = System.currentTimeMillis();
        System.out.println("\ntime ");
        System.out.print(sysDate2 - sysDate1);
    }
}